spring:
  datasource:
    url: jdbc:mysql://47.98.108.191:3666/mongo_es?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: qwe123
  data:
    mongodb:
      uri: mongodb://47.98.108.191:20001/test


